name: agri_notebooks

channels:
  - plotly
  - pyviz
  - conda-forge
  - defaults

dependencies:
  - jupyter-panel-proxy
  - numpy
  - pandas
  - panel>=1
  - plotly
  - pvlib
  - python=3.9
  - scikit-learn>=1.2
