name: app_bilan_hydrique

channels:
  - conda-forge
  - defaults

dependencies:
  - jupyter-panel-proxy
  - numpy>=2.0
  - pandas>=2.2
  - panel>=1.5
  - plotly>=5.24
  - pvlib>=0.11
  - python=3.9
  - scikit-learn>=1.6
