name: agri_notebooks

channels:
  - plotly
  - conda-forge
  - defaults

dependencies:
  - bokeh>=3
  - holoviews
  - hvplot
  - numpy
  - pandas
  - panel>=1
  - plotly
  - pvlib
  - python>=3.9
  - scikit-learn>=1.2
