name: Build Executables with Conda (Mac OS)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"  # Ensures Miniconda is installed
          activate-environment: agri_notebooks
          environment-file: environment.yml
          python-version: 3.9
          auto-update-conda: true

      # Step 3: Initialize Conda and activate environment
      - name: Initialize Conda
        run: |
          conda init zsh
          source ~/.zshrc
          conda activate agri_notebooks

      # Step 4: Verify Conda environment
      - name: Verify Conda Environment
        run: conda info --all

      # Step 5: Install additional dependencies (optional)
      # - name: Install Extra Dependencies
      #   run: |
      #     conda activate agri_notebooks
      #     pip install some_extra_pip_package_if_needed

      # Step 6: Build the executable with PyInstaller
      - name: Build Executable
        run: |
          conda init zsh
          source ~/.zshrc
          conda activate agri_notebooks
          pyinstaller --onefile --add-data "bilan_hydrique_observation_horaire.ipynb:." \
                      --add-data "bilan.py:." \
                      --add-data "meteofrance.py:." \
                      --add-data "geo.py:." \
                      --add-data "etp.py:." \
                      --add-data "coefficients_culturaux_ardepi.json:." \
                      --hidden-import panel \
                      launcher.py

      # Step 7: Upload the build artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos_bilan_hydrique_app
          path: dist/
